[package]
name = "soundlight"
version = "0.1.0"
description = "Local-first music library and player"
edition = "2021"

[lib]
name = "soundlight_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset", "unstable"] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
blake3 = "1"
rusqlite = { version = "0.37", features = ["bundled"] }
lofty = "0.22"
futures-util = "0.3.33"
tauri-plugin-opener = "2.5.4"
reqwest = { version = "0.12", default-features = false, features = [
  "rustls-tls",
  "stream",
  "charset",
] }
url = "2.5.8"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
